# Generated by Django 4.1.6 on 2023-02-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Villager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('personality', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('birthday', models.CharField(max_length=15)),
                ('catchprase', models.CharField(max_length=50)),
            ],
        ),
    ]
