# Generated by Django 4.1.6 on 2023-02-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_home_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='villager',
            name='homes',
            field=models.ManyToManyField(to='main_app.home'),
        ),
    ]
