# Generated by Django 4.1.6 on 2023-02-08 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_villager_homes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='villager',
            old_name='catchprase',
            new_name='catchphrase',
        ),
    ]
