# Generated by Django 4.1.6 on 2023-02-09 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_catchprase_villager_catchphrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='villager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.villager'),
            preserve_default=False,
        ),
    ]
