# Generated by Django 4.1.6 on 2023-02-09 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_note_villager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('villager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.villager')),
            ],
        ),
    ]
