# Generated by Django 4.1.6 on 2023-02-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='villager',
            name='villager_img',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
